# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/omkar.shirdhone/Project/GenAI_SDCL/app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/omkar.shirdhone/Project/GenAI_SDCL/app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/omkar.shirdhone/Project/GenAI_SDCL/app/CMakeFiles /mnt/c/Users/omkar.shirdhone/Project/GenAI_SDCL/app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/omkar.shirdhone/Project/GenAI_SDCL/app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named MyProject

# Build rule for target.
MyProject: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MyProject
.PHONY : MyProject

# fast build rule for target.
MyProject/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/build
.PHONY : MyProject/fast

Environment.o: Environment.cpp.o
.PHONY : Environment.o

# target to build an object file
Environment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/Environment.cpp.o
.PHONY : Environment.cpp.o

Environment.i: Environment.cpp.i
.PHONY : Environment.i

# target to preprocess a source file
Environment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/Environment.cpp.i
.PHONY : Environment.cpp.i

Environment.s: Environment.cpp.s
.PHONY : Environment.s

# target to generate assembly for a file
Environment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/Environment.cpp.s
.PHONY : Environment.cpp.s

Nodel.o: Nodel.cpp.o
.PHONY : Nodel.o

# target to build an object file
Nodel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/Nodel.cpp.o
.PHONY : Nodel.cpp.o

Nodel.i: Nodel.cpp.i
.PHONY : Nodel.i

# target to preprocess a source file
Nodel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/Nodel.cpp.i
.PHONY : Nodel.cpp.i

Nodel.s: Nodel.cpp.s
.PHONY : Nodel.s

# target to generate assembly for a file
Nodel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/Nodel.cpp.s
.PHONY : Nodel.cpp.s

Obstacle.o: Obstacle.cpp.o
.PHONY : Obstacle.o

# target to build an object file
Obstacle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/Obstacle.cpp.o
.PHONY : Obstacle.cpp.o

Obstacle.i: Obstacle.cpp.i
.PHONY : Obstacle.i

# target to preprocess a source file
Obstacle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/Obstacle.cpp.i
.PHONY : Obstacle.cpp.i

Obstacle.s: Obstacle.cpp.s
.PHONY : Obstacle.s

# target to generate assembly for a file
Obstacle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/Obstacle.cpp.s
.PHONY : Obstacle.cpp.s

RRT.o: RRT.cpp.o
.PHONY : RRT.o

# target to build an object file
RRT.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/RRT.cpp.o
.PHONY : RRT.cpp.o

RRT.i: RRT.cpp.i
.PHONY : RRT.i

# target to preprocess a source file
RRT.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/RRT.cpp.i
.PHONY : RRT.cpp.i

RRT.s: RRT.cpp.s
.PHONY : RRT.s

# target to generate assembly for a file
RRT.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/RRT.cpp.s
.PHONY : RRT.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MyProject.dir/build.make CMakeFiles/MyProject.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MyProject"
	@echo "... Environment.o"
	@echo "... Environment.i"
	@echo "... Environment.s"
	@echo "... Nodel.o"
	@echo "... Nodel.i"
	@echo "... Nodel.s"
	@echo "... Obstacle.o"
	@echo "... Obstacle.i"
	@echo "... Obstacle.s"
	@echo "... RRT.o"
	@echo "... RRT.i"
	@echo "... RRT.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

